apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-frontend-deploy
spec:
  replicas: 1
  selector:
     matchLabels:
       app: smsappfront
  template:
    metadata:
      labels:
        app: smsappfront
    spec:

      containers:
      - name: smsappfront
        image: smsacr321.azurecr.io/frontimg1:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        

---
apiVersion: v1
kind: Service
metadata:
  name: sms-frontend-external-svc
spec:
  selector:
    app: smsappfront
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
